package plotter

const PLOTTER_DUR_DATA_LEN = 4
const PLOTTER_FLOAT_DATA_LEN = 2
const PLOTTER_INT_DATA_LEN = 2
const PLOTTER_THROTTLE_DATA_LEN = 1
//2 byte packet size + 2 byte data len + 2 byte data/packet
const PLOTER_PACKET_HEADER_LEN = PLOTTER_INT_DATA_LEN * 3
//4 bytes duration, 18 bytes rotations, 1 byte throttle
const PLOTTER_DATA_LEN = PLOTTER_DUR_DATA_LEN + 9 * PLOTTER_FLOAT_DATA_LEN + PLOTTER_THROTTLE_DATA_LEN
const PLOTTER_DATA_PER_PACKET = 100
const PLOTTER_PACKET_LEN = PLOTER_PACKET_HEADER_LEN + PLOTTER_DATA_PER_PACKET*PLOTTER_DATA_LEN
