package constants

const DUR_DATA_LEN = 4
const DUR_FLOAT_LEN = 2
const INT_DATA_LEN = 2
const PLOTER_PACKET_HEADER_SIZE = 6
const PLOTTER_DATA_LEN = DUR_DATA_LEN + 9*DUR_FLOAT_LEN
const PLOTTER_DATA_PER_PACKET = 256
const PLOTTER_PACKET_SIZE = PLOTER_PACKET_HEADER_SIZE + PLOTTER_DATA_PER_PACKET*PLOTTER_DATA_LEN

const RADIO_PAYLOAD_SIZE uint8 = 6
const JOYSTICK_RANGE_DEG = 180
const THROTTLE_MAX = 200
