package constants

const RADIO_PAYLOAD_SIZE uint8 = 10
const JOYSTICK_RANGE_DEG = 180
const JOYSTICK_DIGITAL_MAX_VALUE = 1024
const THROTTLE_RAW_READING_MAX = 250
const MAX_APPLICABLE_THROTTLE_PERCENT = 33
