flight_control:
  imu_data_per_second: 2500
  lowpass_filter_coefficient: 0.9975
devices:
  icm20948:
    bus_number: 0
    chip_select: 0
    accelerometer:
      sensitivity_level: '8g'
      lowpass_filter_enabled: true
      lowpass_filter_config: 3
      averaging: 7
      offsets:
        X: -65
        Y: 831
        Z: -790
    gyroscope:
      sensitivity_level: '250dps'
      lowpass_filter_enabled: true
      lowpass_filter_config: 3
      averaging: 7
      offsets:
        X: -13
        Y: 0
        Z: 0
udp:
  enabled: true
  ip: 192.168.1.101
  port: 6431
  udp_packets_per_second: 20 # set to zero for disabling udp send
  udp_data_per_second: 320
