flight-control:
  debug: false
  min-throttle: 5
  max-throttle: &MAX_THROTTLE 20
  max-roll: 5
  max-pitch: 5
  max-yaw: 5

  pid:
    roll:
      input-limit: 45
      p-gain: 0
      i-gain: 0
      d-gain: 0
      i-limit: *MAX_THROTTLE
    pitch:
      input-limit: 45
      p-gain: 0
      i-gain: 0
      d-gain: 0
      i-limit: *MAX_THROTTLE
    yaw:
      input-limit: 45
      p-gain: 0
      i-gain: 0
      d-gain: 0
      i-limit: *MAX_THROTTLE
    calibration:
      calibrating: false
      p-step: 0.1
      i-step: 0.1
      d-step: 0.1
  imu:
    data-per-second: 1000
    lowpass-filter-coefficient: 0.01
    accelerometer:
      sensitivity-level: '4g'
      lowpass-filter-enabled: true
      lowpass-filter-config: 3
      averaging: 7
      offsets:
        X: -73
        Y: 825
        Z: -787
    gyroscope:
      sensitivity-level: '500dps'
      lowpass-filter-enabled: true
      lowpass-filter-config: 3
      averaging: 7
      offsets:
        X: -12
        Y: -6
        Z: -8
    spi:
      bus-number: 0
      chip-select: 0
  esc:
    i2c-dev: '/dev/i2c-1'
    update-per-second: 50
    pwm-device-to-esc-mappings:
      0: 0
      1: 4
      2: 8
      3: 12
  radio:
    rx-tx-address: '03896'
    power-dbm: '-12dbm'
    ce-gpio: 'GPIO26'
    heart-beat-timeout-ms: 1000
    spi:
      bus-number: 1
      chip-select: 2
  power-breaker: 'GPIO17'

remote-control:
  command-per-sec: 40
  joysticks:
    roll:
      channel: 4
      offset: -50
      dir: 1
    pitch:
      channel: 2
      offset: -28
      dir: -1
    yaw:
      channel: 3
      offset: -43
      dir: 1
    throttle:
      channel: 5
      offset: -1
    spi:
      bus-number: 0
      chip-select: 0
  buttons:
    front-left: 'GPIO15'
    front-right: 'GPIO22'
    top-left: 'GPIO17'
    top-right: 'GPIO27'
    bottom-left: 'GPIO18'
    bottom-right: 'GPIO23'
  radio:
    rx-tx-address: '03896'
    power-dbm: '-12dbm'
    ce-gpio: 'GPIO26'
    heart-beat-timeout-ms: 1000
    spi:
      bus-number: 1
      chip-select: 2
  display-i2c-address: 0x3D
  buzzer-gpio: 'GPIO5'

logger:
  enabled: false
  ip: 192.168.1.101
  port: 6431
  packets-per-second: 50
