flight_control:
  pid:
    proportional–gain: 1
    integral-gain: 0
    derivative-gain: 0 
  imu:
    imu_data_per_second: 3200
    acc_lowpass_filter_coefficient: 0.005
    lowpass_filter_coefficient: 0.01
  esc:
    update_frequency: 50
    max_throttle: 15 # a float between 0 100
    device: '/dev/i2c-1'
    power_breaker_gpio: 'GPIO17'
    motors:
      0:
        label: 'A'
        esc_channel: 0
      1: 
        label: 'B'
        esc_channel: 4
      2:
        label: 'C'
        esc_channel: 8
      3:
        label: 'D'
        esc_channel: 12

devices:
  icm20948:
    bus_number: 0
    chip_select: 0
    accelerometer:
      sensitivity_level: '8g'
      lowpass_filter_enabled: true
      lowpass_filter_config: 3
      averaging: 7
      offsets:
        X: -65
        Y: 831
        Z: -790
    gyroscope:
      sensitivity_level: '250dps'
      lowpass_filter_enabled: true
      lowpass_filter_config: 3
      averaging: 7
      offsets:
        X: -12
        Y: -6
        Z: -8
    magnetometer:
      sensitivity_level: '0'

udp:
  enabled: true
  ip: 192.168.1.103
  port: 6431
  packets_per_second: 20 # set to zero for disabling udp send
  max_data_per_packet: 20
