remote:
  buttons:
  - button-l0: 
    name: "GPIO2"
  - button-l1:  
    name: "GPIO3"
  - button-l2:  
    name: "GPIO4"
  - button-l3:  
    name: "GPIO17"
  - button-l4:  
    name: "GPIO27"
  - button-r0:  
    name: "GPIO14"
  - button-r1:  
    name: "GPIO15"
  - button-r2:  
    name: "GPIO18"
  - button-r3:  
    name: "GPIO23"
  - button-r4:  
    name: "GPIO24"

