flight-control:
  imu:
    data-per-second: 3200
    acc-lowpass-filter-coefficient: 0.005
    lowpass-filter-coefficient: 0.01
    accelerometer:
      sensitivity-level: '8g'
      lowpass-filter-enabled: true
      lowpass-filter-config: 3
      averaging: 7
      offsets:
        X: -65
        Y: 831
        Z: -790
    gyroscope:
      sensitivity-level: '250dps'
      lowpass-filter-enabled: true
      lowpass-filter-config: 3
      averaging: 7
      offsets:
        X: -12
        Y: -6
        Z: -8
    spi:
      bus-number: 0
      chip-select: 0

remote-control:
  mcp3008:
    spi:
      bus_number: 0
      chip_select: 0
      mode: 0
      speed-mega-hz: 1
  x-channel: 2
  y-channel: 4
  z-channel: 3
  throttle-channel: 5
  joysticks:
    roll:
      channel: 2
      zero-value: 2.5
    pitch:
      channel: 4
      zero-value: 2.6
    yaw:
      channel: 3
      zero-value: 2.4
    v-ref: 5
    spi:
      bus-number: 0
      chip-select: 0
      mode: 0
      speed-mega-hz: 1
  throttle:
    channel: 5
  buttons:
    front-left: 'GPIO27'
    front-right: 'GPIO17'
    top-left: 'GPIO22'
    top-right: 'GPIO15'
    down-left: 'GPIO18'
    down-right: 'GPIO23'
  v-ref: 5

logger:
  enabled: true
  ip: 192.168.1.101
  port: 6431
  packets-per-second: 20 # set to zero for disabling udp send
  max-data-per-packet: 20