flight-control:
  debug: false
  min-throttle: 10
  max-throttle: 50
  max-roll: 5
  max-pitch: 5
  max-yaw: 5
  arm-0-2-throttle-ratio: 1
  arm-1-3-throttle-ratio: 1

  pid:
    roll:
      p-gain: 2
      i-gain: 5
      d-gain: 0.25
      max-i-to-max-throttle-ratio: 0.5
    pitch:
      p-gain: 0
      i-gain: 0
      d-gain: 0
      max-i-to-max-throttle-ratio: 0.5
    yaw:
      p-gain: 0
      i-gain: 0
      d-gain: 0
      max-i-to-max-throttle-ratio: 0.1
    calibration:
      calibrating: 'roll'
      gain: 'p'
      p-step: 0.1
      i-step: 0.1
      d-step: 0.01
  imu:
    data-per-second: 1000
    complimentary-filter-coefficient: 0.001
    accelerometer:
      sensitivity-level: '4g'
      lowpass-filter-enabled: true
      lowpass-filter-config: 3
      averaging: 7
      offsets:
        X: 32696
        Y: 836
        Z: 31979
    gyroscope:
      sensitivity-level: '500dps'
      lowpass-filter-enabled: true
      lowpass-filter-config: 3
      averaging: 7
      offsets:
        X: 0
        Y: 0
        Z: 4
      directions:
        X: 1
        Y: -1
        Z: 1
    spi:
      bus-number: 0
      chip-select: 0
  esc:
    i2c-dev: '/dev/i2c-1'
    update-per-second: 50
    pwm-device-to-esc-mappings:
      0: 0
      1: 4
      2: 8
      3: 12
  radio:
    rx-tx-address: &RX_TX_ADDRESS '03896'
    ce-gpio: 'GPIO26'
    connection-timeout-ms: &HEART_BEAT_TIMEOUT 250
    spi:
      bus-number: 1
      chip-select: 2
  command-per-sec: &COMMAND_PER_SECOND 20
  power-breaker: 'GPIO17'

remote-control:
  command-per-sec: *COMMAND_PER_SECOND
  joysticks:
    roll:
      channel: 4
      offset: -50
      dir: 1
    pitch:
      channel: 2
      offset: -28
      dir: -1
    yaw:
      channel: 3
      offset: -43
      dir: 1
    throttle:
      channel: 5
      offset: 5
    spi:
      bus-number: 0
      chip-select: 0
  buttons:
    front-left: 'GPIO15'
    front-right: 'GPIO22'
    top-left: 'GPIO17'
    top-right: 'GPIO27'
    bottom-left: 'GPIO18'
    bottom-right: 'GPIO23'
  radio:
    rx-tx-address: *RX_TX_ADDRESS
    ce-gpio: 'GPIO26'
    connection-timeout-ms: *HEART_BEAT_TIMEOUT
    spi:
      bus-number: 1
      chip-select: 2
  display-i2c-address: 0x3D
  buzzer-gpio: 'GPIO5'

logger:
  enabled: false
  ip: 192.168.1.102
  port: 6431
  packets-per-second: 50
