flight_control:
  imu_data_per_second: 3200
  lowpass_filter_coefficient: 0.999
devices:
  icm20948:
    bus_number: 0
    chip_select: 0
    accelerometer:
      sensitivity_level: 3
      offsets:
        - X: 0
          Y: 0
          Z: 0
        - X: 0
          Y: 0
          Z: 0
        - X: 0
          Y: 0
          Z: 0
        - X: -25
          Y: -7
          Z: 37
    gyroscope:
      sensitivity_level: 3
      lowpass_filter_enabled: true
      lowpass_filter_config: 3
      averaging: 7
      offsets:
        - X: 0
          Y: 0
          Z: 0
        - X: 0
          Y: 0
          Z: 0
        - X: 0
          Y: 0
          Z: 0
        - X: 3.1629
          Y: 1
          Z: 0.7
udp:
  enabled: true
  ip: 192.168.1.102
  port: 6431
  udp_packets_per_second: 20 # set to zero for disabling udp send
  udp_data_per_second: 320
