flight_control:
  pid:
    proportional–gain: 1
    integral-gain: 0
    derivative-gain: 0 
  imu:
    imu_data_per_second: 1000
    acc_lowpass_filter_coefficient: 0.005
    lowpass_filter_coefficient: 0.01
  esc:
    # max_esc_pulse_width is float between 1 to 1.5
    max_esc_pulse_width_ms: 1.2

devices:
  icm20948:
    bus_number: 0
    chip_select: 0
    accelerometer:
      sensitivity_level: '8g'
      lowpass_filter_enabled: true
      lowpass_filter_config: 3
      averaging: 7
      offsets:
        X: -65
        Y: 831
        Z: -790
    gyroscope:
      sensitivity_level: '250dps'
      lowpass_filter_enabled: true
      lowpass_filter_config: 3
      averaging: 7
      offsets:
        X: -12
        Y: -6
        Z: -8

udp:
  enabled: true
  ip: 192.168.1.103
  port: 6431
  udp_packets_per_second: 20 # set to zero for disabling udp send
  udp_data_per_second: 320
