flight_control:
  imu_data_per_second: 4000
  accelerometer_lowpass_filter_coefficient: 0.15
  rotations_lowpass_filter_coefficient: 0.05
devices:
  icm20948:
    bus_number: 0
    chip_select: 0
    accelerometer:
      sensitivity_level: 3
      offsets:
        - X: 0
          Y: 0
          Z: 0
        - X: 0
          Y: 0
          Z: 0
        - X: 0
          Y: 0
          Z: 0
        - X: 0
          Y: 0
          Z: 0
    gyroscope:
      scale_level: 2
      lowpass_filter_enabled: true
      lowpass_filter_config: 3
      averaging: 7
      offsets:
        - X: 0
          Y: 0
          Z: 0
        - X: 0
          Y: 0
          Z: 0
        - X: 3.8160075
          Y: 5.97310
          Z: 6.07156
        - X: 0
          Y: 0
          Z: 0
udp:
  enabled: true
  ip: 192.168.1.101
  port: 6431
