flight-control:
  imu-data-per-second: 3200
  esc-update-per-second: 100
  pid:
    p-gain: 0
    i-gain: 0
    d-gain: 0
    analog-input-to-roll-conversion:
      ratio: 0.1
      offset: 0
    analog-input-to-pitch-conversion:
      ratio: 0.1
      offset: 0
    analog-input-to-yaw-conversion:
      ratio: 0.1
      offset: 0
    analog-input-to-throttle-conversion: 
      ratio: 0.1
      offset: 0

  imu:
    acc-lowpass-filter-coefficient: 0.005
    lowpass-filter-coefficient: 0.01
    accelerometer:
      sensitivity-level: '8g'
      lowpass-filter-enabled: true
      lowpass-filter-config: 3
      averaging: 7
      offsets:
        X: -65
        Y: 831
        Z: -790
    gyroscope:
      sensitivity-level: '250dps'
      lowpass-filter-enabled: true
      lowpass-filter-config: 3
      averaging: 7
      offsets:
        X: -12
        Y: -6
        Z: -8
    spi:
      bus-number: 0
      chip-select: 0
  esc:
    i2c-dev: '/dev/i2c-1'
    max-throttle: 15
    motors-esc-mappings:
      0: 0
      1: 4
      2: 8
      3: 12
  radio:
    ce-gpio: 'GPIO26'
    rx-tx-address: '03896'
    power-dbm: '-12dbm'
    spi:
      bus-number: 1
      chip-select: 2
  power-breaker: 'GPIO17'

remote-control:
  joysticks:
    roll:
      channel: 2
      zero-value: 2.5
    pitch:
      channel: 4
      zero-value: 2.6
    yaw:
      channel: 3
      zero-value: 2.4
    throttle:
      channel: 5
      zero-value: 0
    v-ref: 5
    spi:
      bus-number: 0
      chip-select: 0
  buttons:
    front-left: 'GPIO15'
    front-right: 'GPIO22'
    top-left: 'GPIO17'
    top-right: 'GPIO27'
    bottom-left: 'GPIO18'
    bottom-right: 'GPIO24'
  v-ref: 5

radio-connetion:
  command-per-second: 20
  heartbeat-per-second: 4
  command-timeout-ms: 250
  heartbeat-timeout-ms: 750

logger:
  enabled: true
  ip: 192.168.1.100
  port: 6431
  packets-per-second: 50
