#inertial motion unit
imu:
  data_per_second: 500
  filter_coefficient: 0.01

icm20789:
  gyroscope:
    full_scale: "250dps" #values: [250dps, 500dps, 1000dps, 2000dps] (dps=degree per second)
    offsets:
      x: 11
      y: 12
      z: 13
  accelerometer:
    full_scale: "2g" #values: [2g, 4g, 8g, 16g]
    offsets:
      x: 14
      y: 15
      z: 16
