flight-control:
  debug: false
  max-throttle: 40
  safe-start-throttle: 9.8
  control-variable-range: 40.2
  pid:
    roll-pitch-p-gain: 1.2
    roll-pitch-i-gain: 0
    roll-pitch-d-gain: 0
    max-roll: 10.5
    max-pitch: 10.5
    yaw-p-gain: 0.2
    yaw-i-gain: 0.0001
    yaw-d-gain: 0
    max-yaw: 15
    max-i: 13.5
    axis-alignment-angle: 45
    calibration-gain: 'roll-d'
    calibration-step: 0.1
  imu:
    data-per-second: 3200
    acc-lowpass-filter-coefficient: 0.005
    lowpass-filter-coefficient: 0.01
    accelerometer:
      sensitivity-level: '8g'
      lowpass-filter-enabled: true
      lowpass-filter-config: 3
      averaging: 7
      offsets:
        X: -65
        Y: 831
        Z: -790
    gyroscope:
      sensitivity-level: '250dps'
      lowpass-filter-enabled: true
      lowpass-filter-config: 3
      averaging: 7
      offsets:
        X: -12
        Y: -6
        Z: -8
    spi:
      bus-number: 0
      chip-select: 0
  esc:
    i2c-dev: '/dev/i2c-1'
    update-per-second: 50
    pwm-device-to-esc-mappings:
      0: 0
      1: 4
      2: 8
      3: 12
  radio:
    rx-tx-address: '03896'
    power-dbm: '-12dbm'
    ce-gpio: 'GPIO26'
    heart-beat-timeout-ms: 1000
    spi:
      bus-number: 1
      chip-select: 2
  power-breaker: 'GPIO17'

remote-control:
  command-per-sec: 40
  joysticks:
    roll:
      channel: 4
      offset: -50
      dir: 1
    pitch:
      channel: 2
      offset: -28
      dir: -1
    yaw:
      channel: 3
      offset: -43
      dir: 1
    throttle:
      channel: 5
      offset: -1
    spi:
      bus-number: 0
      chip-select: 0
  buttons:
    front-left: 'GPIO15'
    front-right: 'GPIO22'
    top-left: 'GPIO17'
    top-right: 'GPIO27'
    bottom-left: 'GPIO18'
    bottom-right: 'GPIO23'
  radio:
    rx-tx-address: '03896'
    power-dbm: '-12dbm'
    ce-gpio: 'GPIO26'
    heart-beat-timeout-ms: 1000
    spi:
      bus-number: 1
      chip-select: 2
  display-i2c-address: 0x3D
  buzzer-gpio: 'GPIO5'

logger:
  enabled: true
  ip: 192.168.1.101
  port: 6431
  packets-per-second: 50
