push-buttons:
  push-button-left-0: "GPIO5"
  push-button-left-1: "GPIO6"
  push-button-left-2: "GPIO4"
  push-button-left-3: "GPIO17"
  push-button-left-4: "GPIO27"
  push-button-right-0: "GPIO14"
  push-button-right-1: "GPIO15"
  push-button-right-2: "GPIO18"
  push-button-right-3: "GPIO23"
  push-button-right-4: "GPIO22"
