push-buttons:
  push-button-right-0: "GPIO4"
  push-button-right-1: "GPIO14"
  push-button-right-2: "GPIO15"
  push-button-right-3: "GPIO18"
  push-button-right-4: "GPIO23"
  push-button-left-0: "GPIO17"
  push-button-left-1: "GPIO27"
  push-button-left-2: "GPIO22"
  push-button-left-3: "GPIO5"
  push-button-left-4: "GPIO6"
